import fs from 'node:fs'
import path from 'node:path'
import type { Plugin, ViteDevServer } from 'vite'

const FIREBASE_SW_FILE = 'firebase-messaging-sw.js'

const buildServiceWorker = (): string => {
  const config = {
    apiKey: process.env.VITE_FIREBASE_API_KEY || '',
    authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN || '',
    projectId: process.env.VITE_FIREBASE_PROJECT_ID || '',
    storageBucket: process.env.VITE_FIREBASE_STORAGE_BUCKET || '',
    messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
    appId: process.env.VITE_FIREBASE_APP_ID || '',
  }

  return `/* eslint-disable */
// Generated by Vite. Client Firebase config only — never put Admin secrets here.
importScripts('https://www.gstatic.com/firebasejs/12.17.1/firebase-app-compat.js')
importScripts('https://www.gstatic.com/firebasejs/12.17.1/firebase-messaging-compat.js')

const firebaseConfig = ${JSON.stringify(config, null, 2)};
const isConfigured = Object.values(firebaseConfig).every(Boolean);

if (isConfigured && !firebase.apps.length) {
  firebase.initializeApp(firebaseConfig);
}

const messaging = isConfigured ? firebase.messaging() : null;

const buildNotificationOptions = (payload) => {
  const data = payload.data || {};
  const title = (payload.notification && payload.notification.title) || data.title || 'Drivoo';
  const body = (payload.notification && payload.notification.body) || data.body || '';
  return {
    title,
    options: {
      body,
      data: {
        url: data.url || '/',
        type: data.type || '',
      },
      tag: data.tag || 'drivoo-fcm',
      renotify: false,
    },
  };
};

if (messaging) {
  messaging.onBackgroundMessage((payload) => {
    // FCM already displays messages that include a notification payload.
    if (payload.notification) {
      return;
    }
    const { title, options } = buildNotificationOptions(payload);
    return self.registration.showNotification(title, options);
  });
}

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const targetUrl = (event.notification.data && event.notification.data.url) || '/';
  event.waitUntil((async () => {
    const windowClients = await clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const client of windowClients) {
      if ('focus' in client) {
        await client.focus();
        if ('navigate' in client && targetUrl) {
          await client.navigate(targetUrl);
        }
        return;
      }
    }
    if (clients.openWindow) {
      await clients.openWindow(targetUrl);
    }
  })());
});
`
}

export const firebaseMessagingSwPlugin = (): Plugin => {
  const writeDevFile = () => {
    const publicDir = path.resolve(process.cwd(), 'public')
    if (!fs.existsSync(publicDir)) {
      fs.mkdirSync(publicDir, { recursive: true })
    }
    fs.writeFileSync(path.join(publicDir, FIREBASE_SW_FILE), buildServiceWorker())
  }

  return {
    name: 'firebase-messaging-sw',
    configureServer(server: ViteDevServer) {
      writeDevFile()
      server.middlewares.use((req, res, next) => {
        if (req.url?.split('?')[0] !== `/${FIREBASE_SW_FILE}`) {
          next()
          return
        }
        res.setHeader('Content-Type', 'application/javascript; charset=utf-8')
        res.setHeader('Service-Worker-Allowed', '/')
        res.end(buildServiceWorker())
      })
    },
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: FIREBASE_SW_FILE,
        source: buildServiceWorker(),
      })
    },
  }
}
